---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - На странице корзины пользователь может удалить товар из корзины
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты
  - На странице корзины пользователь может продолжить выбирать товары в каталоге. 
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен корректно отображаться на мобильных устройствах. 
  - Cайт не должен перезагружать страницу (должен поддерживать одностраничный формат)
  - В каталоге должна отображаться цена каждого товара (со скидкой и без скидки)
  - В описании каждого товара должна отображаться цена товара (со скидкой и без скидки)
  - Корзина должна храниться в сессии браузера. 
implicit:
  - Сайт должен соотвествовать правилам GDPR
  
